### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by TimeBandit** [facelessuser/ExportHtml#24]
Hello,

I really want to use this with ST2 but your readme does not contain information for me, a new user. So I dont know how to install it. What I did try didnt work. I tried installing the repo as you would with ST3 but even that showed me no menu options. 

Please advide

**Comment by TimeBandit** [comment]
I think I got it installed now but cant figure out

**Comment by facelessuser** [comment]
[Package Control](https://packagecontrol.io/installation) is your friend.  This is the recommended way to install any and all plugins.  This allows you to automatically get updates.
