### ISSUE TITLE
Would like a setting to ignore the fact that some text is selected when exporting

### ISSUE THREAD

**Issue by Doodpants** [facelessuser/ExportHtml#27]
Suppose you have some text selected. If "highlight_selections" is true, it exports the entire file, and highlights the selected bit. If "highlight_selections" is false, it only exports the selected text. What I would like is a setting in which it exports the entire file, and ignores the fact that some of the text happens to be selected, not highlighting it at all. I don't like having to consciously make sure that there is no text selected before I go to export the file.

**Comment by facelessuser** [comment]
This is scheduled for release `st3-1.4.0`.  The code has been committed here: https://github.com/facelessuser/ExportHtml/commit/55d610438b1fdb78af60b1fb534b980ffd0b2db1.
