### ISSUE TITLE
contextual menu items dimmed

### ISSUE THREAD

**Issue by hobbes444** [facelessuser/ExportHtml#28]
Probably a noob mistake from me, but I just installed exporthtml using package control on ST2 and when I right click selected text, the “HTML” and “BBCode” options are always dimmed (grayed out).
I use OS X 10.10.2.

**Comment by facelessuser** [comment]
Are you getting any errors in the console?

**Comment by facelessuser** [comment]
It's been a week with no additional info.  I will give this a couple more days, then I will close the issue.

**Comment by facelessuser** [comment]
I assume your problem is solved, or you do not want to divulge any further info to help me close this issue.  Since I cannot move forward with the current details, I will close the issue.

**Comment by hobbes444** [comment]
Sorry about that, I am not used yet to multiple inbox in gmail and I
completely missed your email. There are some errors indeed: “No module
named HtmlAnnotations” for example.

Cheers,
Cyprien

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/hobbes/Library/Application Support/Sublime Text
2/Packages
settings path: /Users/hobbes/Library/Application Support/Sublime Text
2/Settings
PackageSetup not required
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/0_package_control_loader/02-bz2.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./02-bz2.py", line 2, in <module>
    from package_control import sys_path
ImportError: No module named package_control
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/CSS/css_completions.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/comment.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/copy_path.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/delete_word.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/detect_indentation.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/duplicate_line.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/echo.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/exec.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/fold.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/font.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/goto_line.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/indentation.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/kill_ring.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/mark.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/new_templates.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/open_file_settings.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/open_in_browser.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/paragraph.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/scroll.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/side_bar.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/sort.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/swap_line.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/switch_file.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/transform.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/transpose.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Diff/diff.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportBbcode.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ExportBbcode.py", line 5, in <module>
    from ExportHtml.lib.color_scheme_matcher import ColorSchemeMatcher
  File "./ExportHtml.py", line 8, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportHtml.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ExportHtml.py", line 8, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/HtmlAnnotations.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./HtmlAnnotations.py", line 3, in <module>
    from ExportHtml.lib.notify import error
  File "./ExportHtml.py", line 8, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Filter Lines/Filter Lines.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/HTML/html_completions.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Package Control/Package Control.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/Package Control/bootstrap.py
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/StyleToken/StyleToken.py
plugin init time: 0.285379
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.803249
using gpu buffer for window
using gamma: 2 (err: 6.9282)
startup cache, total files: 102 cache hits: 102
startup time: 1.19583 (package setup was not run)
loaded 837 snippets
Package Control: Installing 1 upgrades
ignored packages updated to: [Vintage, ExportHtml]
found 1 files for base name Default.sublime-theme
Unloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportBbcode.py
Unloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportHtml.py
Unloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/HtmlAnnotations.py
found 3 files for base name Main.sublime-menu
reloading /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/User/Package Control.sublime-settings
reloading /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: Upgraded ExportHtml to v2015.05.15.22.53.32
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/User/Package Control.sublime-settings
reloading /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportBbcode.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ExportBbcode.py", line 6, in <module>
    from ExportHtml.lib.color_scheme_matcher import ColorSchemeMatcher
  File "./ExportHtml.py", line 9, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/ExportHtml.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ExportHtml.py", line 9, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
Reloading plugin /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/ExportHtml/HtmlAnnotations.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./HtmlAnnotations.py", line 4, in <module>
    from ExportHtml.lib.notify import error
  File "./ExportHtml.py", line 9, in <module>
    from ExportHtml.HtmlAnnotations import get_annotations
ImportError: No module named HtmlAnnotations
found 4 files for base name Main.sublime-menu
theme loaded
reloading /Users/hobbes/Library/Application Support/Sublime Text
2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
