### ISSUE TITLE
Bold and italic not exporting to bbcode

### ISSUE THREAD

**Issue by Zeblote** [facelessuser/ExportHtml#29]
To reproduce, try these steps:
- Create a new file in Sublime Text 3
- Select the default Eiffel color scheme.
- Set language to C# and enter this code:
```
public class Example
{
    public void Test(string str) { }
}
```
- `Example` and `str` should be in italics, `Test` should be bold.
- Export to bbcode using "Sublime View - Show BBCode in View"
- The result will look like this:
```
[pre=#FFFFFF][color=#000000]public[/color][color=#000000] class[/color][color=#000000] Example[/color]
[color=#000000]{[/color]
[color=#000000]    public[/color][color=#000000] void[/color][color=#0000A2] Test[/color][color=#000000]([/color][color=#000000]string[/color][color=#0206FF] str[/color][color=#000000])[/color][color=#000000] {[/color][color=#000000] }[/color]
[color=#000000]}[/color]
[/pre]
```

Bold and Italic markups are missing from the code.

General info:
- Windows 8.1 Pro (64 bit)
- Sublime Text 3 Build 3083 (64 bit)
- Installed Package Manager to download ExportHtml (ST3 branch)

**Comment by facelessuser** [comment]
Fixed in latest commit: https://github.com/facelessuser/ExportHtml/commit/b564b8ad621484ef7248267fbfce9e08a6088ad2.

Will be available in the next release.
