### ISSUE TITLE
Show BBCode in view with gutter misses lines

### ISSUE THREAD

**Issue by Zeblote** [facelessuser/ExportHtml#30]
Selecting "Show BBCode in View (show gutter)" doesn't produce the same result as "Format as BBCode (show gutter"), the line numers are missing.

**Comment by facelessuser** [comment]
The code is fine, but the default setting for that option was misconfigured (you can tell how much I use that option).  But the settings file has been updated with the proper configuration. Fix in commit https://github.com/facelessuser/ExportHtml/commit/e56d3ca684a81149451828294bd4db0941068378.

Fix will be in the next release.
