### ISSUE TITLE
Fix non-ASCII file path support

### ISSUE THREAD

**Issue by kakaja** [facelessuser/ExportHtml#32]
Hello,

I don't manage to  use your plugin in Sublime Text build 3083 on osX 10.10.3.
I get the following in the console:

    Traceback (most recent call last):
     File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 211, in execute
      File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 782, in run
      File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 680, in write_body
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-146: ordinal not in range(128)
    DEBUG:TS:call get_event from on_idle
    DEBUG:TS:asking for errors

Please, can you tell me what I have to do to make it work?
Thank you!

**Comment by facelessuser** [comment]
As this is working for me, you are going to have to provide more info http://facelessuser.github.io/ExportHtml/contributing/#bug-reports.

- How did you install ExportHTML?  Manually or Package Control.
- Are you using ST2 or ST3?
- Are you sure you have the right branch of ExportHtml for the right version of Sublime Text?
- Please provide steps to reproduce the problem, that includes a snippet of failing code (obviously post something that you are okay with sharing; don't post anything proprietary or private).  Please note the encoding of the text you are providing.

**Comment by kakaja** [comment]
Thank you for fast reply! Here are the answers to your questions:

1. ExportHTML installed via Package Control.

2. ST3: Sublime Text build 3083

3. *>Are you sure you have the right branch of ExportHtml *
I am not sure, but I suppose that installing via Package Manager gives the right branch automatically.

4. *>Please provide steps to reproduce the problem*
I have a simple typescript file with this content:
```typescript
//angular/modules/angular2/src/router/route_handler.ts

import {Promise, PromiseWrapper} from 'angular2/src/facade/async';
import {Type} from 'angular2/src/facade/lang';

export interface RouteHandler {
  componentType: Type;
  resolveComponentType(): Promise<any>;
}
```

I click right anywhere in the file body, select "Export", then "HTML, then in the appeared window any of the options: "Browser Print - Color, Browser Print - Grayscale, etc..." I have tried all of them, the result is the same. Nothing happens. Here is the console log during all these actions, that I have just described: 

```
DEBUG:TS:on_text_command
DEBUG:TS:on_text_command_with_info
DEBUG:TS:on_activated
DEBUG:TS:on_activated_with_info
DEBUG:TS:on_window_command
DEBUG:TS:on_activated
DEBUG:TS:on_activated_special_view
DEBUG:TS:on_post_text_command
DEBUG:TS:call get_event from on_idle
DEBUG:TS:asking for errors
DEBUG:TS:Posting command: {"arguments": {"files": ["/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"], "delay": 500}, "type": "request", "command": "geterr", "seq": 2822}
DEBUG:TS:Read body of length: 132
DEBUG:TS:Read body of length: 601
DEBUG:TS:call get_event from on_idle
DEBUG:TS:asking for errors
DEBUG:TS:on_activated
DEBUG:TS:on_activated_with_info
DEBUG:TS:Posting command: {"arguments": {"formatOptions": {"indentSize": 2, "convertTabsToSpaces": false, "tabSize": 2}, "hostInfo": "Sublime Text version 3083", "file": "/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"}, "type": "request", "command": "configure", "seq": 2823}
DEBUG:TS:Posting command: {"arguments": {"formatOptions": {"indentSize": 2, "convertTabsToSpaces": false, "tabSize": 2}, "hostInfo": "Sublime Text version 3083", "file": "/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"}, "type": "request", "command": "configure", "seq": 2824}
DEBUG:TS:Posting command: {"arguments": {"formatOptions": {"indentSize": 2, "convertTabsToSpaces": false, "tabSize": 2}, "hostInfo": "Sublime Text version 3083", "file": "/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"}, "type": "request", "command": "configure", "seq": 2825}
Traceback (most recent call last):
  File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 211, in execute
  File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 782, in run
  File "ExportHtml in /Users/John/Library/Application Support/Sublime Text 3/Installed Packages/ExportHtml.sublime-package", line 680, in write_body
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-146: ordinal not in range(128)
DEBUG:TS:Read body of length: 84
DEBUG:TS:Body sequence#: 2823
DEBUG:TS:Read body of length: 84
DEBUG:TS:Body sequence#: 2824
DEBUG:TS:Read body of length: 84
DEBUG:TS:Body sequence#: 2825
DEBUG:TS:call get_event from on_idle
DEBUG:TS:asking for errors
DEBUG:TS:Posting command: {"arguments": {"file": "/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts", "tmpfile": "/Users/John/Library/Application Support/Sublime Text 3/Packages/TypeScript/.tmpbuf116"}, "type": "request", "command": "reload", "seq": 2826}
DEBUG:TS:Posting command: {"arguments": {"files": ["/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"], "delay": 500}, "type": "request", "command": "geterr", "seq": 2827}
DEBUG:TS:Read body of length: 81
DEBUG:TS:Body sequence#: 2826
DEBUG:TS:Read body of length: 132
DEBUG:TS:Read body of length: 601
DEBUG:TS:call get_event from on_idle
DEBUG:TS:asking for errors
```


These are the packages that I have installed in my ST (just copied from /Application Support/Sublime Text 3/Installed Packages/):

0_package_control_loader.sublime-package
Dimmed Color Scheme.sublime-package
PyV8
Angular Material Snippets.sublime-package
Emmet.sublime-package
Sass.sublime-package
AngularJS.sublime-package
Enhanced HTML and CFML.sublime-package
SideBarEnhancements.sublime-package
AutoFileName.sublime-package
ExportHtml.sublime-package
Syntax Highlighting for Sass.sublime-package
Better TypeScript.sublime-package
Frontend Light Color Scheme.sublime-package
SyntaxHighlightTools.sublime-package
CSS Completions.sublime-package
HTMLAttributes.sublime-package
Theme - Elementary.sublime-package
CSS3.sublime-package
JavaScriptNext - ES6 Syntax.sublime-package
Tomorrow Color Schemes.sublime-package
Clipboard Manager.sublime-package
LastModifiedIndicator.sublime-package
Tully Color Schemes.sublime-package
Color Schemes by carlcalderon.sublime-package
Package Control.sublime-package
TypescriptCompletion.sublime-package
ColorSchemeSelector.sublime-package
Paraiso Color Scheme.sublime-package
jQuery.sublime-package
Demain Color Scheme.sublime-package
Pretty JSON.sublime-package





Please, let me know if you need more info or tests from my side.

**Comment by facelessuser** [comment]
There is nothing at all wrong with the content of the file.  It is all ascii, so there can't possibly be an encoding issue with the content.

But your error is an encoding issue.

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-146: ordinal not in range(128)
```

But I did see some odd stuff in your log.  Does this pertain to the file in question?  Does your file name contain non-ascii characters?  It is possible this is your problem.  ExportHtml might not handle non-ascii file paths well:

```
DEBUG:TS:Posting command: {"arguments": {"files": ["/Users/John/Desktop/_info/_\u0441\u0441\u044b\u043b\u043a\u0438/000_test.ts"], "delay": 500}, "type": "request", "command": "geterr", "seq": 2827}
```

Let me know so I can hopefully get to the bottom of this.

**Comment by kakaja** [comment]
Ooooooo! Thank you! Effectively, the folder name of this file had non-ascii caracters! :) It works perfectly with folder name changed.

**Comment by facelessuser** [comment]
Glad you got it working.  I should still probably fix this though.
