### ISSUE TITLE
Suppress time-stamp etc. on first line

### ISSUE THREAD

**Issue by jyoshimi** [facelessuser/ExportHtml#36]
Great package, thanks!   I didn't see anything in the settings file that allows the time-stamp, file location, etc. at the top of the file to be suppressed (or the stuff at the bottom). I'd like a way to print something that is as close to a direct mapping from sublimetext to printout as possible, with no additional things displayed.

Sorry if this is right in front of me somewhere.

**Comment by facelessuser** [comment]
All the parameters for a given export rule are found here: http://facelessuser.github.io/ExportHtml/usage/#exporting-html.  You can modify the rule(s) of interest and set `date_time_format` to an empty string.

**Comment by jyoshimi** [comment]
Oh crap so it was right in front me.   Thanks very much!

**Comment by facelessuser** [comment]
No worries, glad you got it figured out.
