### ISSUE TITLE
Maintain indentations and wordwrappping in html

### ISSUE THREAD

**Issue by jyoshimi** [facelessuser/ExportHtml#39]
Hello,

I am wondering if it is possible to add a setting where indentations and wordwrap in sublimetext carry over to the exported html.   E.g. this page

<img width="809" alt="screen shot 2016-03-07 at 10 17 32 am" src="https://cloud.githubusercontent.com/assets/10526604/13578642/06d408d0-e44e-11e5-8f30-72bba77933bc.png">

when exported to html, produces a file where long lines just get truncated from the browser window instead of being wrapped and indented,  e.g. like this

<img width="771" alt="screen shot 2016-03-07 at 10 22 14 am" src="https://cloud.githubusercontent.com/assets/10526604/13578747/a989fc42-e44e-11e5-845b-900109a239a1.png">

I hope I'm  not overlooking some documentation again like last time I posted an issue (I did check!) and I suspect there is no easy solution on this, but thought it was worth a shot.  Thanks!

**Comment by facelessuser** [comment]
Wrapping is possible.  There is usually a tooltip in the upper right hand corner that appears on mouse over that has a wrap icon.  You can also configure existing export commands to use wrapping, or create your own export command that does wrapping.  See the command options: http://facelessuser.github.io/ExportHtml/usage/#exporting-html.

**Comment by jyoshimi** [comment]
Thanks for the quick response!  Sorry if I'm being dense here.   When I set that setting, I get things like this

<img width="932" alt="screen shot 2016-03-07 at 1 58 42 pm" src="https://cloud.githubusercontent.com/assets/10526604/13584741/c3497766-e46c-11e5-8770-acf33ced0892.png">

Here I have set wrapping to 900, but the indentation is not lined up the same way it is in sublimetext.   Can that be addressed?

**Comment by facelessuser** [comment]
Okay, normal, physical indentation is kept and wrapping can be initiated as I showed.

What isn't done is specialized intelligent wrap indentation.  Meaning I don't format the HTML to be wrapped.  It's just done with some JavaScript and CSS.  I don't scan and calculate how much the current line is indented and then reformat the text to then be indented just as much.  ExportHTML exports the text as is and exports the characters.  It then applies the wrapping CSS via JavaScript if desired.  You would have to hard wrap it by inserting the newlines and tabs/spaces if you wanted it exported as you show in Sublime.  ExportHTML just exports the characters with the current style.

**Comment by jyoshimi** [comment]
Ok got it, thanks again for the help.    It would be a nice feature, but from the sounds of it, not an easy one to implement.

**Comment by facelessuser** [comment]
You could always write a plugin to hard wrap your content and then export it.  I think others have written hard wrap plugins: https://packagecontrol.io/packages/AutoWrap.  Maybe something like that might help.

**Comment by jyoshimi** [comment]
Ah yes, ok, nice idea.  Thanks!

**Comment by jyoshimi** [comment]
Success with this package

https://github.com/ehuss/Sublime-Wrap-Plus

Done!
