### ISSUE TITLE
[Feature Request] Export Code Block

### ISSUE THREAD

**Issue by Enteleform** [facelessuser/ExportHtml#40]
First of all, this plugin is epic!&nbsp; I checked out the `Sublime View` output, and it's pretty crazy how you were able to deconstruct the code + syntax & repackage it into `HTML`. :smiley:
&nbsp;

-----

&nbsp;
The feature request is based on the issue of copying exported code back to an editor.

Currently, if you attempt to do so, this happens:

![animation 1](https://cloud.githubusercontent.com/assets/10906415/14245172/69a93fda-fa2d-11e5-9cce-75fc5dcb0bb1.gif)

&nbsp;
I think that is similar, if not the same, as the problem described in [**Issue #26**](https://github.com/facelessuser/ExportHtml/issues/26).

&nbsp;
So that got me thinking, is it possible to export to a code block similar to the SublimeText forum?

**For example:**
![codeblock](https://cloud.githubusercontent.com/assets/10906415/14245220/c127d8fc-fa2d-11e5-801a-901ba7e02e53.PNG)
&nbsp;

-----

&nbsp;
The benefits are:

* it does not require wrapping, so code can be displayed as it was written
* code can be easily copied into an editor
* easy to include & isolate multiple code samples so the page doesn't end up crazy long

&nbsp;
Some improvements upon the standard code block could be:

* custom colors based on `tmTheme` files ( *as you currently have* )
* a line number section on the side that does not interfere with text selection
* @ `sublime-settings` : options for [ min | max ] height & width

&nbsp;
I'm not sure if this could be done entirely in `HTML`, but it would still be pretty cool even if it required a bit of extra work to implement on the user side.&nbsp; :smile:

**Comment by facelessuser** [comment]
If you move the mouse to the upper right corner, a toolbox will appear where you can hide the gutter and the gutter lines will no longer be copied.  You can also modify the existing command options or create your own and disable the gutter with the `number` parameter: http://facelessuser.github.io/ExportHtml/usage/#exporting-html.

**Comment by facelessuser** [comment]
I will consider this issue closed as hiding the gutter is already possible via on demand or by default.
