### ISSUE TITLE
[Feature request] "line-height" option

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/ExportHtml#41]
In my work sometimes I need in my documents to insert the text in the blank forms and then print documents. Example:

![Elections](http://i.imgur.com/F6OHryk.jpg)

The picture shows that the text is either above or forms, where I should insert the text. Leading turns big. I can not do so that `20 .`and `Черкесск` are positioned on the black parallel lines, when big font size. So I have to change the font size or should I edit my documents that I need to print, in HTML.

I have read the [documentation](http://facelessuser.github.io/ExportHtml/usage/) on the use of ExportHTML plugin, but I did not find the option of leading change. I think that this option should be. I need it, maybe other users of your plugin, this option is also useful.

Thanks.

**Comment by facelessuser** [comment]
Hi @Kristinita, I am looking over your request, but I am having a little difficult understanding the request.  I'm having a hard time making the connection of the form you are showing me and the HTML output ExportHTML renders.

What I think I do understand is that you want an option to control the CSS line height.  Most likely, if I do this, I may just allow the insertion of additional CSS to override or append additional styling...maybe I might just allow you to point to your own CSS template.  I don't really understand the use case with forms, but I think I can make the CSS styling more flexible.

**Comment by Kristinita** [comment]
> but I am having a little difficulty understanding the request

I want, that in `ExportHtml.sublime-settings` → settings of color scheme, for example, `"color_scheme": "Packages/ExportHtml/ColorSchemes/Print-Grayscale.tmTheme"`, → I could assign a parameter `line-height` as in CSS, for example, `"line-height": 70%,`, so that I can change the line spacing.

Thanks.

**Comment by facelessuser** [comment]
Okay, I understand.  I will see how I want to approach this when I get the time.

**Comment by facelessuser** [comment]
New setting has been added to address this.  You can now specify the path to your own CSS.  For example, you can copy the original CSS from `Packages/ExportHtml/css/export.css` to `Packages/User/export.css`.  Modify what you want in your custom copy, and change the setting to point to yours.

```js
    // Export HTML CSS.
    "export_css": "Packages/User/export.css",
```

**Comment by Kristinita** [comment]
I add in my `User/export.css`

```css
div {
	line-height: 2rem;
}
```

Thank you very much! Great work!
