### ISSUE TITLE
ExportHTML: HTML option is grayed out

### ISSUE THREAD

**Issue by 0004072** [facelessuser/ExportHtml#45]
I am running Sublime Text 3 on Ubuntu 16.04 LTS 64bit. Once I set this package up, I have realized that the option "HTML" on the "Export" menu item in the right click menu is grayed out. I have tried reinstalling and restarting many times. But still no good. The same when I tried in Windows, it works perfectly. Please sort this out.

Following are the support info.
- ST ver.: 3103
- Platform: linux
- Arch: x64
- Plugin ver.: 2.3.1
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- markdown ver.: Version could not be acquired!
- pygments ver.: 2.2a0
- jinja2 ver.: Version could not be acquired!

The BBCode option is available and it works.

**Comment by facelessuser** [comment]
You will need to follow the issue template you were presented with to get help.  Please update the your opening post with the required info.  If you do not remember what the template asked for, you can find it here: https://github.com/facelessuser/ExportHtml/blob/master/.github/ISSUE_TEMPLATE.md. Please fix as the info you've provided is not sufficient for me debug

Also, I'm not seeing your issue on a clean install.
