### ISSUE TITLE
Automatically open browser tab with "Browser Print"

### ISSUE THREAD

**Issue by julienlapointe** [facelessuser/ExportHtml#46]
## Description

> - Selecting "Browser Print" opens a new Sublime Text tab with a temporary HTML file (always starts with "tmp"), which I then Build to open the Chrome tab with the print dialog. Is there a way for "Browser Print" to Build and close the "tmp" HTML file so that I jump to the Chrome browser tab with print dialog? This would be helpful when printing many files.  
> - I feel as though this feature existed in the past, but I cannot find any mention of it in the docs or Settings - Default file. I am currently using ST Build 3126 and Chrome Version 56.0.2924.87 (64-bit).

**Comment by facelessuser** [comment]
Please update the opening post following the template: https://github.com/facelessuser/ExportHtml/blob/master/.github/ISSUE_TEMPLATE.md.  I need versions and more details.  Are you using default commands, or custom commands?

**Comment by facelessuser** [comment]
I don't see this issue.  `Browser Print` opens in the browser; no Sublime tabs are created.  This is with the latest version.  I suspect you are overriding with personal settings that are incorrect.  I am marking this invalid as there is not enough info in the opening post (per the template).  Also, I would need to see your personal ExportHtml settings to be sure you are not overriding with bad values. I will leave this open for a week and close it if not updated with the requested info, but currently, I see no issues.

**Comment by julienlapointe** [comment]
Thanks for the reply. I uninstalled, then re-installed ExportHtml so I should be using the latest version too. 

Here are the customizations in my Settings - User file:

{
	"html_panel": 
	[
		{
			"Browser Print - Color":
			{
				"numbers": true,
                		"wrap": 1100,
                		"browser_print": true,
                		"multi_select": true,
				"color_scheme": "Packages/Boxy Theme/schemes/Boxy Yesterday.tmTheme",
                		"style_gutter": false,
                		"show_full_path": false,
                		"view_open": true
			}
		}
	]
}

Did I make any mistakes? I have only been coding for a year.

Thank you,
 
Julien

Julien LaPointe
647.625.4878

**Comment by facelessuser** [comment]
> Thanks for the reply. I uninstalled, then re-installed ExportHtml so I should be using the latest version too.

Understood, but next time please do follow instructions listed in the template for getting the version of the plugin and the version of its dependencies.  It really helps which is why I request it.

> Did I make any mistakes? I have only been coding for a year.

There are some issues, but it has nothing to do with coding, you are just setting the wrong settings.  Please read the list of settings in the table here in the documentation: http://facelessuser.github.io/ExportHtml/usage/#exporting-html.  Particular `view_open` is forcing content to open in a Sublime view opposed to the browser.  I didn't look at all your settings, but I'll let you read about each setting to learn what they do.  Also, you can reference the default print examples if you are looking for working print examples: https://github.com/facelessuser/ExportHtml/blob/master/ExportHtml.sublime-settings#L44.

**Comment by facelessuser** [comment]
Haven't heard a response in 29 days, so I am assuming this answered your question.  Closing issue.

**Comment by julienlapointe** [comment]
Hi Isaac,

Apologies for the long delay. 

Here is a video of the issue: https://www.dropbox.com/s/7a4ozmp8ub6my8x/ExportHTML%20Issue.mov?dl=0. I press Cmd + Shift + P to open the palette, select ExportHTML > Browser Print - Color, which opens a new Sublime tab with the formatting for Chrome. I then press Cmd + B to open the file in Chrome and the print dialog appears automatically.

I have attached the default and my user settings for ExportHTML.

Thank you,
 
Julien

Julien LaPointe
647.625.4878

**Comment by facelessuser** [comment]
I don't see an attachment.  Did you look at the docs like I mentioned in my answer?

> Please read the list of settings in the table here in the documentation: http://facelessuser.github.io/ExportHtml/usage/#exporting-html. Particular view_open is forcing content to open in a Sublime view opposed to the browser. I didn't look at all your settings, but I'll let you read about each setting to learn what they do. Also, you can reference the default print examples if you are looking for working print examples: https://github.com/facelessuser/ExportHtml/blob/master/ExportHtml.sublime-settings#L44.

**Comment by julienlapointe** [comment]
Yes, I looked at your docs. I have re-attached the settings files. 

Thank you,
 
Julien

Julien LaPointe
647.625.4878

**Comment by facelessuser** [comment]
Please don't respond via email with attachments.  Come directly to the issue and post your settings.  GitHub will not deliver your attachments to me.

**Comment by julienlapointe** [comment]
Here are my settings: [ExportHTM_Settings.zip](https://github.com/facelessuser/ExportHtml/files/1073298/ExportHTM_Settings.zip)

**Comment by julienlapointe** [comment]
Here are my settings: [ExportHTML_Settings.zip](https://github.com/facelessuser/ExportHtml/files/1073303/ExportHTML_Settings.zip)

**Comment by julienlapointe** [comment]
I finally figured out what was wrong. I set "view_open": true in my settings. The Docs state that "browser_print": true gets ignored if "view_open": true. Hopefully this thread saves time for anyone who made the same mistake. @facelessuser Apologies for taking your time!

**Comment by facelessuser** [comment]
That is what I mentioned earlier, but I'm glad you got it working. Hopefully this will help others in the future.
