### ISSUE TITLE
cannot see html view on Ubuntu 16.04

### ISSUE THREAD

**Issue by gigony** [facelessuser/ExportHtml#47]
## Description

gnome-open doesn't exist in Ubuntu 16.04 so 'Browser - View' command doesn't work.

Please check this information:
https://askubuntu.com/questions/68961/what-can-i-use-instead-of-gnome-open

P.S. Thanks for the great plug-in! :+1:

**Comment by facelessuser** [comment]
This was back when I was using the Desktop module to pull off open files.   I don't really use that anymore in other projects, so I will likely remove it and put in what I do elsewhere.

**Comment by facelessuser** [comment]
Pushed a fix.  Hopefully that works well for you.  I'll make a release sometime this weekend.

**Comment by gigony** [comment]
Thanks!

**Comment by facelessuser** [comment]
2.4.1 released.
