### ISSUE TITLE
Every tab is converted into (in my case) 4 spaces

### ISSUE THREAD

**Issue by devvithelopper** [facelessuser/ExportHtml#55]
## Description

Every tab character is converted to (in my case) 4 spaces, while it should be converted into 1, 2, 3 or 4 depending on the alignement I am trying to produce. In other words the following table should look like this (the browser prints tabs as 8 characters though, but I think you get the idea) on output:

```
============================================================
T	Tp	Sp	D	Dp	S	D7	T
------------------------------------------------------------
A	F#m	Bm	E	C#m	D	E7	A
A#	Gm	Cm	F	Dm	D#	F7	A#
B♭	Gm	Cm	F	Dm	E♭m	F7	B♭
```

but it looks like this:

```
============================================================
T    Tp    Sp    D    Dp    S    D7    T
------------------------------------------------------------
A    F#m    Bm    E    C#m    D    E7    A
A#    Gm    Cm    F    Dm    D#    F7    A#
B♭    Gm    Cm    F    Dm    E♭m    F7    B♭
```

## Support Info

- ST ver.: 3143
- Platform: osx
- Arch: x64
- Plugin ver.: 2.10.2
- Install via PC: True
- mdpopups ver.: 3.1.3
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Export to HTML: Show Export Menu
2. Browser Print: Color

**Comment by facelessuser** [comment]
Currently, tabs are converted.  I'll consider possibly changing this, we'll see how it goes.

**Comment by facelessuser** [comment]
Okay, never mind, I know what the issue is.  Tabs need to be equal Sublime's tab width, but they may possibly be shorter if other characters consume part of the tab width.  I'll look into this.

**Comment by facelessuser** [comment]
Conversion of tabs will be based on actual tab stops, but you can use the `disable_nbsp` option to use real tabs and spaces if desired.  Copying and pasting into emails with `disable_nbsp` enabled may not work as expected (for instance Outlook), so use in export commands that are appropriate.

**Comment by devvithelopper** [comment]
Hey again, sorry that I did not report back on this, it kind of slipped my mind. Thanks for the good work. This worked nicely. 

Now I needed it again and the old behaviour is back. I used "Browser View - Color" with default settings and the tab distance is screwed up again. What happened?

To clarify: for me it does not matter wether it's spaces or tabs or nbsp. The only thing important is that the export looks like the original.

Thanks in advance. I'll be sure to report back on you this time.

Current Support Info:

- ST ver.: 3143
- Platform: osx
- Arch: x64
- Plugin ver.: 2.12.1
- Install via PC: True
- mdpopups ver.: 3.3.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by devvithelopper** [comment]
Oh my dear, I am sorry. Your changes work as expected. 

The issue this time is different. I used the "♭" character (musical flat) and the monospace font used in the browser does not display the ♭ with a width of 1 character but rather 1.5 characters. This is what screwed up my output. I guess you can do nothing about that.

As workaround one could either use another font or use actual tab characters in the browser. Is that possible in the options? I haven't found it in the user guide...
