### ISSUE TITLE
Need some help changing the color_scheme

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [facelessuser/ExportHtml#58]
## Steps to Reproduce Issue

See here for all required info and a detailed description. Perhaps you can help me out on this one since you know the most about it. https://stackoverflow.com/questions/48087699/how-do-i-change-the-color-scheme-used-by-the-exporthtml-package-in-sublime-text

**Comment by facelessuser** [comment]
I appreciate the link, but in the future, please provide support information in the issue as well.

As for your issue, there is no way to simply append currently.  You'll have to copy the entire menu and add or modify the rule you want.

As for color scheme, you edit the `color_scheme` parameter with the path to you color scheme (starting at Packages).  Package Control installs most packages under `Installed Packages` as zip files, but internally, they are accessed as if they were unzipped in `Packages`.  So based on the the color scheme plugin's [documentation](https://github.com/evandrocoan/NotepadPlusPlusColorScheme#manual-installation), it seems like you'd access the color scheme with the path `Packages/Notepad++ Theme/Default Stylers.tmTheme`.

**Comment by ElectricRCAircraftGuy** [comment]
Thanks! Issue closed. 
I used `"color_scheme": "Packages/Notepad++ Color Scheme/Default Stylers.tmTheme",`
It worked.
