### ISSUE TITLE
Minor comment error in sublime-settings file

### ISSUE THREAD

**Issue by artBoffin** [facelessuser/ExportHtml#59]
Line 135 in the sublime-settings file is

// Sublime view grayscale HTML source; (selections and multi-selections allowed)

should be

// Sublime view color HTML source; (selections and multi-selections allowed)

**Comment by hadisfr** [comment]
I think this issue can be closed now. 🤔

**Comment by facelessuser** [comment]
Looks like it, thanks!  I have so many repos, some of these things get overlooked...
