### ISSUE TITLE
New color schemes and copyright issues

### ISSUE THREAD

**Issue by hadisfr** [facelessuser/ExportHtml#61]
There is the following statement in [readme.md](https://github.com/facelessuser/ExportHtml/blob/master/readme.md):
> Print-Color and Print-Grayscale tmThemes were derived from Monokai Bright.

What was that _Monokai Bright_? Was that the original sublime's one?

If so, can we add other default sublime color schemes (e.g. Breakers, Celeste, Mariana, Monoka, and Sixteen) to project without violating copyright law?

**Comment by facelessuser** [comment]
There is no need to add other schemes.  You can use any scheme you want already without adding them.  I just wanted some basic print schemes: color and black and white.  We could revamp the current ones to use the new color scheme format and target the new official scopes though.

*Monokai Bright* was originally from the old Sublime, which was most likely a derivative or copy from textmate. Just about every color scheme out there is derived from an existing one.  It is rare for one to be done completely from scratch.

The new Sublime color schemes I think were done from scratch as they are a completely new format taking advantage of Sublime specific things, but every color scheme is usually based off these originals with probably a few exceptions.

People make derivatives of these and add a license, but what are they copyrighting?  The color palette? Assigning color to  a specific scope? Most of the time they are taking most of the scopes being assigned from the other schemes.  I don't know.  I just mentioned where it came from to be honest, but the reality is no one really cares. If someone requests me to do something extra, I'll be more than happy to.
