### ISSUE TITLE
Backround color set to "none" in Print-Color.sublime-color-scheme turned into white

### ISSUE THREAD

**Issue by BLTSIZE** [facelessuser/ExportHtml#63]
## Description

Cannot set the background color to "none" in Print-Color.sublime-color-scheme: the background color of the spans which class is "real_text" in the generated HTML document is set to white ("#FFFFFF") instead.

It is important to be able to specify "none" and get "none" in the end, because if you copy-paste the generated HTML in a Word document, you will never be able to remove the background-color unless it is set to "none" in this HTML document.

## Support Info

- ST ver.: 3207
- Platform: windows
- Arch: x64
- Plugin ver.: 2.13.0
- Install via PC: True
- mdpopups ver.: 3.4.0
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Install ExportHTML
2. Select Preferences / Color Scheme...
3. Select Print-Color
4. Select Tools / Packages / Packages Development / Edit Current Color Scheme...
5. Update the "globals" section like this:

```
"globals": {
	"background": "none",
},
```

6. Load some source, click the right mouse button and select Export / HTML
7. Select "Browser View - Color"
8. Look at the source code for the HTML page:

`
<span class=" real_text" style="background-color: #FFFFFF; color: #000000;">
`

So the background color is not "none", it is "#FFFFFF". Notice that the background color would have been set to whatever otherwise (for example: "red" gives "#FF0000").

**Comment by facelessuser** [comment]
How does Sublime represent such backgrounds? As I recall Sublime always has a background color even if you omit the background, and any transparent backgrounds for scope are mixed with that background. ExportHTML mimics this. `none` isn't directly translated to HTML to mean no color. A matter of fact, I don't even no if Sublime views `none` as a valid option for `background`.

Regardless, ExportHTML will never assume no background, it must have some kind of background. The question is what does Sublime do with such a color scheme? What background does Sublime give in this case?

**Comment by BLTSIZE** [comment]
The documentation reports [here](https://www.sublimetext.com/docs/3/color_schemes.html) that ST3 supports the alpha channel in the color scheme. May this allow a workaround? Indeed, if you copy / paste HTML from Firefox to Word, Word will not retain colors which alpha is set to any value. So if the generated HTML file contains :

`<span  style="background-color: #FF00007F">This is a test</span>`

You may copy-paste from Firefox to Word, and "This is a test" will not have any background color in Word, althrough it is displayed with a semi-transparent red background in Firefox.

So the trick may be to allow to specify an alpha channel in the colors of the Print-Color for the background? At this time, if you set an alpha value for the background in this scheme like this:

```
"globals": {
	"background": "#FF00007F",
},
```

...the alpha value is discarded in the generated HTML file:

`<span class=" real_text" style="background-color: #FF0000; color: #000000;">`

Hence a problem...

**Comment by facelessuser** [comment]
I don't understand what you want. Does the color not match what you see in Sublime? I am less concerned with how it copies to Word right now. I want to find out if the background looks like it should in Sublime.
