### ISSUE TITLE
Cannot recognize the view setting "font_option"

### ISSUE THREAD

**Issue by absop** [facelessuser/ExportHtml#64]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ExportHtml/) related to your specific question, issue, or request.

---

## Description
The plugin cannot recognize the setting "font_option", for example, if I add the setting "font_options": ["no_italic"] for C language,**ExportHtml** cannot obey the setting.  

## Support Info

I open this issue for hoping you can add support for this setting.

## Steps to Reproduce Issue

Thanks.

**Comment by facelessuser** [comment]
Sorry I didn't see this issue before. This seems like a reasonable request. As I have time, I will consider adding this.

@gir-bot add T: feature P: maybe

**Comment by facelessuser** [comment]
@gir-bot add T: feature, P: maybe

**Comment by absop** [comment]
> Sorry I didn't see this issue before. This seems like a reasonable request. As I have time, I will consider adding this.
> 
> @gir-bot add T: feature P: maybe

Thanks for your great works and reply!
