### ISSUE TITLE
Export XML

### ISSUE THREAD

**Issue by turbo** [facelessuser/ExportHtml#68]
## Description

Add the capability of exporting XML, which reflects the scoped syntax tree. Here's an example:

```bash
#!/bin/bash

echo "Word: ${1}!"
```

```xml
<source.shell.bash>
  <comment.line.number-sign.shell> 
    <punctuation.definition.comment.begin.shell>
      <token column="1" line="1" content="#"/>
    </punctuation.definition.comment.begin.shell>
    <token column="2" line="1" content="!/bin/bash"/>
  </comment.line.number-sign.shell>
  <meta.function-call.shell>
    <support.function.echo.shell>
      <token column="1" line="3" content="echo"/>
    </support.function.echo.shell>
  </meta.function-call.shell>
  <meta.function-call.arguments.shell>
    <token column="5" line="3" content=" "/>
    <string.quoted.double.shell>
      <punctuation.definition.string.begin.shell>
        <token column="6" line="3" content="&quot;"/>
      </punctuation.definition.string.begin.shell>
      <token column="7" line="3" content="Word: "/>
      <meta.group.expansion.parameter.shell> 
        <punctuation.definition.variable.shell>
          <token column="13" line="3" content="$"/>
        </punctuation.definition.variable.shell>
        <punctuation.section.expansion.parameter.begin.shell>
          <token column="14" line="3" content="{"/>
        </punctuation.section.expansion.parameter.begin.shell>
        <variable.other.readwrite.shell>
          <token column="15" line="3" content="1"/>
        </variable.other.readwrite.shell>
        <punctuation.section.expansion.parameter.end.shell>
          <token column="16" line="3" content="}"/>
        </punctuation.section.expansion.parameter.end.shell>
      </meta.group.expansion.parameter.shell>
      <token column="17" line="3" content="!"/>
      <punctuation.definition.string.end.shell>
        <token column="18" line="3" content="&quot;"/>
      </punctuation.definition.string.end.shell>
    </string.quoted.double.shell>
  </meta.function-call.arguments.shell>
</source.shell.bash>
```

This would allow for the analysis of source files in external programs (using structural query engines like XPath).

Scanning the API and [this repo's source code](https://github.com/facelessuser/ExportHtml/blob/4bd5739169f93d3a8c6a9d1579ec1a7c170de7b0/ExportHtml.py#L759), `scope_name` seems to be the underlying API which could support this. I suspect a streaming XML generator would be required because it is important to preserve the order of sibling nodes in the XML tree. Speed could be another issue, but I have no experience with either Python or the Sublime API to judge that.

**Comment by facelessuser** [comment]
@turbo I can see why people may like something like this, but unfortunately, it doesn't really fit the scope of the project.

The motivation behind ExportHtml was to export code content in such a way I could copy and past into outlook from HTML, print the HTML, and output BBCode (because forums that used BBCode where more popular then -- it is probably less relevant these days...maybe I could drop BBCode :thinking:). That is really the scope of this project.

While I think being able to navigate scopes in XML is interesting, [ScopeHunter](https://github.com/facelessuser/ScopeHunter) has mainly been my tool for such things. Or better put, it fits the extent of my scope analysis needs.

When I look at adding new features, these days, I am a bit more critical about what additional features I add, as I then must support them. Unfortunately, this is not a feature I have a need for, and secondly, it really doesn't fit within this projects scope.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by turbo** [comment]
Understood, thanks. I might give this a go in a separate plugin. I've seen ScopeHunter, though it's functionality is already built into ST3 and ST4, and other scope related plugins just re-package the example script provided by Sublime.

 A follow-up question:

As far as I understand, this plugin parses highlighted scope regions iteratively and resolves their style, which is probably the approach (together with a streaming XML writer) that I would take. Did you ever compare the performance of this against ST's built-in HTML export to see if there's a significant difference?

**Comment by facelessuser** [comment]
> Understood, thanks. I might give this a go in a separate plugin. I've seen ScopeHunter, though it's functionality is already built into ST3 and ST4, and other scope related plugins just re-package the example script provided by Sublime.

If all you need is scope than yup. I use it for the color reporting along with scope. I'm not really plugging it as much as just saying that is the extend of analysis that I've ever needed. My personal needs are simple in this area.

> As far as I understand, this plugin parses highlighted scope regions iteratively and resolves their style, which is probably the approach (together with a streaming XML writer) that I would take. Did you ever compare the performance of this against ST's built-in HTML export to see if there's a significant difference?

It simply grabs basic info like scope etc. using Sublime's API, then uses the color scheme it has parsed to approximate what the colors should be. The actual Sublime API recently provides even more info than it did when this was written. Now things like the `style_for_scope` method is available which may or may not make things even easier. We have a whole framework already built up here, so I haven't bothered re-evaluating a refactor as of yet. Not sure if it could give us exactly what we have now or not 🤷‍♂ .

As far as performance, no, I've never compared timings syntax highlighting to our syntax highlighting approximation. I imagine Sublime is faster, but the way in which we use ExportHtml, this has never been a problem.

**Comment by facelessuser** [comment]
As there is no actionable item, I am closing this issue.
