### ISSUE TITLE
I don't seem to get the current color scheme colors on the export.

### ISSUE THREAD

**Issue by mrillusi0n** [facelessuser/ExportHtml#80]
I'm on Sublime Text 3, and the extension has changed to `.sublime-theme` from the older `.tmTheme`. Is it possible to bring support to ST3? I could not get the current color scheme adhering export when I set the `alternate_scheme` in its settings.

**Comment by facelessuser** [comment]
By default, ExportHtml is setup to solve people's biggest issue, printing. So it has default entries that print grayscale and prints in color. Basic schemes are provided for this purposes, and the default commands use those: https://github.com/facelessuser/ExportHtml/blob/master/ExportHtml.sublime-settings#L43.

You would need to override this setting with an option that does not set the color scheme, then it will use whatever is your active color scheme:

```js
        {
            "Browser View - Current Color (example)": {}
        },
```

It's possible that I should provide one of these by default, but I haven't in the past. Anyways, just copy the default `html_panel` setting and add, remove, or modify any entries you would like. The key for controlling color schemes is to either manually specify one in your entry's `color_scheme` option, or to  not specify one at all to get the current color scheme.

@gir-bot remove S: triage
@gir-bot add T: support
