### ISSUE TITLE
Grayscale print option shows up same HTML as colored one

### ISSUE THREAD

**Issue by mohitWrangler** [facelessuser/ExportHtml#86]
---

## Description

Export to HTML grayscale option does not work as expected. The grayscale option produces the same HTML as the colored one.  It looks like that the ExportHtml.sublime-package file contains grayscale color scheme file -- "Packages/ExportHtml/ColorSchemes/Print Grayscale.sublime-color-scheme" but still the grayscale does not show up in HTML page. 

## Support Info

- ST ver.: 3211
- Platform: linux
- Arch: x64
- Plugin ver.: 2.17.1
- Install via PC: True
- mdpopups ver.: 4.1.2
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1.  `ctrl+shift+p` -> Export to HTML: Show export menu -> Browser Print - Grayscale

the above step produces same output as `ctrl+shift+p` -> Export to HTML: Show export menu -> Browser Print - Color.   

## terminal output when using color first then grayscale option

tweaked! ('#f7f1ff', None)
tweaked! (None, '#222222')
tweaked! ('#525053', None)
not tweak
tweaked! ('#f7f1ff', '#222222')
not tweak
not tweak
tweaked! ('#f7f1ff', None)
tweaked! (None, '#222222')
tweaked! ('#525053', None)
not tweak
tweaked! ('#f7f1ff', '#222222')
not tweak
not tweak

## screenshots 
 
![in_sublime_text](https://user-images.githubusercontent.com/5771169/113310287-1224f280-92d6-11eb-8fbe-15cd60598018.png)

![in browser](https://user-images.githubusercontent.com/5771169/113310331-1ea94b00-92d6-11eb-89da-0a0ba7623cc1.png)

**Comment by facelessuser** [comment]
Ugh, I got some debug crap in there.

**Comment by facelessuser** [comment]
The first issue is that the print statements need to be removed 🙃 .

Let me try with default settings. But while I'm add it, try running `Satisfy Dependencies` and then when it finishes in the console, restart Sublime Text.

**Comment by mohitWrangler** [comment]
ok

**Comment by facelessuser** [comment]
Oh, I know what the issue is. We dropped our old parser, and we are now using Sublime's API to get the color scheme info. But when we use a defined color scheme the current view isn't set to it....

**Comment by mohitWrangler** [comment]
I tried `Satisfy Dependencies` and restart. It did not resolve the issue

**Comment by facelessuser** [comment]
Yup, I should have a fix coming, the issue is known.

**Comment by facelessuser** [comment]
I have a fix that has just been released. It may take Package Control an hour or two to see it and update it, but if you need a fix now, enable `legacy_color_matcher` in the ExportHtml settings.

We are moving away from our own Sublime color scheme parser as there are some dark areas that are difficult for us to get right correctly (namely scopes that are being mapped to other scopes for backward compatibility, but there is no official list of what is getting mapped). It just lowers the maintenance cost by dropping our parser moving forward. It's mainly the scope to color matching that is the issue, not the color parsing itself, but when we use the Sublime API, we no longer need to parse the color scheme.
