### ISSUE TITLE
README documentation link broken

### ISSUE THREAD

**Issue by blake-regalia** [facelessuser/ExportHtml#91]
## README documentation link broken

The current URL in the README to the documentation points to a deprecated github.com GitHub Pages site: 
https://facelessuser.github.io/ExportHtml/

Should be updated to: https://facelessuser.github.com/ExportHtml

![Screen Shot 2021-09-07 at 10 12 41 AM](https://user-images.githubusercontent.com/1456400/132384856-c8ddd83a-fdba-4159-ae24-79eaefcc9a02.png)

**Comment by facelessuser** [comment]
Thanks! It was deployed to gh-pages 2 days ago, so something went wrong. I'm attempting to re-deploy.

**Comment by facelessuser** [comment]
Ah, the old link format was deprecated.

**Comment by facelessuser** [comment]
Fixed in readme and on github project site. Will remain broken from packagecontrol.io until another release is cut.
